
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Sat Oct 31 13:31:31 PDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_WHILE = 63;
  public static final int T_INT_LITERAL = 66;
  public static final int T_FLOAT = 26;
  public static final int T_LTE = 38;
  public static final int T_ELSE = 20;
  public static final int T_STATIC = 58;
  public static final int T_RPAREN = 53;
  public static final int T_CONTINUE = 16;
  public static final int T_DELETE = 18;
  public static final int T_COUT = 17;
  public static final int T_SIZEOF = 55;
  public static final int T_NULLPTR = 45;
  public static final int T_FALSE = 25;
  public static final int T_INT = 32;
  public static final int T_MINUSMINUS = 40;
  public static final int T_EXTERN = 24;
  public static final int T_ASSIGN = 5;
  public static final int T_BAR = 7;
  public static final int T_RETURN = 52;
  public static final int T_NOT = 44;
  public static final int T_AND = 3;
  public static final int T_CONST = 15;
  public static final int T_SLASH = 56;
  public static final int T_COLONCOLON = 13;
  public static final int T_GT = 29;
  public static final int T_STRUCTDEF = 59;
  public static final int T_RBRACKET = 51;
  public static final int T_DOT = 19;
  public static final int EOF = 0;
  public static final int T_MINUS = 39;
  public static final int T_TILDE = 61;
  public static final int T_LBRACE = 34;
  public static final int error = 1;
  public static final int T_SEMI = 54;
  public static final int T_NEW = 43;
  public static final int T_ID_U = 68;
  public static final int T_FLOAT_LITERAL = 65;
  public static final int T_MOD = 41;
  public static final int T_RBRACE = 50;
  public static final int T_NEQ = 42;
  public static final int T_CIN = 11;
  public static final int T_COMMA = 14;
  public static final int T_STAR = 57;
  public static final int T_GTE = 30;
  public static final int T_ENDL = 21;
  public static final int T_EQU = 22;
  public static final int T_CARET = 10;
  public static final int T_BOOL = 8;
  public static final int T_PLUS = 48;
  public static final int T_EXIT = 23;
  public static final int T_LT = 37;
  public static final int T_STR_LITERAL = 67;
  public static final int T_THIS = 60;
  public static final int T_OR = 46;
  public static final int T_AMPERSAND = 2;
  public static final int T_BREAK = 9;
  public static final int T_TRUE = 62;
  public static final int T_ISTREAM = 33;
  public static final int T_FOREACH = 27;
  public static final int T_OSTREAM = 47;
  public static final int T_IF = 31;
  public static final int T_PLUSPLUS = 49;
  public static final int T_ARROW = 4;
  public static final int T_ID = 69;
  public static final int T_COLON = 12;
  public static final int T_FUNCTION = 28;
  public static final int T_AUTO = 6;
  public static final int T_VOID = 64;
  public static final int T_LBRACKET = 35;
  public static final int T_LPAREN = 36;
}

